name: Health check

on:
  push:
    branches:
      - master
# on:
#   schedule:
#     - cron: '00 09 * * *'
  
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://full-stack-open-pokedex-smie8.herokuapp.com/health"
          max-attempts: 3
          retry-delay: 5s