name: Hello World!

on:
  push:
    branches:
      - master
  
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Show date
        run: |
          date
  directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Show directory content
        run: |
          ls